language: python
python:
  - "3.4"
# command to install dependencies
install: pip install -r requirements.txt
before_script:
  - flake8 --exclude app/dbmodels --exclude fill_db.py app
  - flake8 test.py
  - flake8 run.py
script: python test.py -v
branches:
  only:
    - master
