language: python
python:
  - "3.4"
# command to install dependencies
install: pip install -r requirements.txt
before_script:
  - flake8 --exclude app/dbmodels --exclude fill_db.py app
  - flake8 run.py
script: 
  - python3 -m nose --with-coverage
  - coverage report -m --fail-under=10

branches:
  only:
    - master
